def heart(percent, space): #this creates a heart with the love percentage in it
    print("  __         __")
    print(" /  \       /  \ ")
    print("/    \     /    \ ")
    print("\     \   /     /")
    print(" \     \ /     /")
    print("  \           /")
    print("   \   " + percent + " "*space + "%   /")
    print("    \       /")
    print("     \     /")
    print("      \   /")
    print("       \ /")
    print("")